layout_spectrum: 0.6575392
color:
  saturation: 0.6795017
  lightness: 0.4776356
  brandStrength: 0.3477797
  brandColors:
    - '#545B5A'
    - '#070606'
    - '#C6A391'
  rhythmicContrast: 0.8511475
typography_spectrum: 0.8137379
name: Michael Gideon Sherry
